version: '3'
services:
  jupyter:
    build:
      context: ./build
      dockerfile: Dockerfile
    # https://hub.docker.com/r/tensorflow/tensorflow
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data:/tf/notebooks
    ports:
      - 8888:8888